### ISSUE TITLE
wandb.errors.CommError: Permission denied, ask the project owner to grant you access

### ISSUE THREAD

**Issue by akritikts** [FedML-AI/FedIoT#2]
I am trying to run the centralised experiments from this link: https://github.com/FedML-AI/FedIoT/tree/main/experiments/centralized

Executing the following files: 
run_ae_cen_glb_test.sh and
ae_cen_glb_test.py results in the error

**Comment by zhang-tuo-pdf** [comment]
Hi,

What kind of error do you meet? Please let me remind you that you need to download the data from the uci website before running and set your local data path correctly.

The dataset website is https://archive.ics.uci.edu/ml/datasets/detection_of_IoT_botnet_attacks_N_BaIoT.

**Comment by zhang-tuo-pdf** [comment]
Hi,

For your case, I think you should configure your own wandb or just delete all the commends related to the wandb. Wanbd stands for the Weights & Biases and it is online result logging system. You could check the settings on https://wandb.ai/home

**Comment by zhang-tuo-pdf** [comment]
Also, I help you to remove all the wandb settings, you could try the new version now and see if the error still happens.

**Comment by zhang-tuo-pdf** [comment]
What is more, you need to download the data from the UCI website and setup your own global testset. The dataset website is here https://archive.ics.uci.edu/ml/datasets/detection_of_IoT_botnet_attacks_N_BaIoT
